USE alx_book_store;
SELECT 
    book_id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(130) NOT NULL,
    author_id INT,
    price DOUBLE,
    publication_date DATE,
    FOREIGN KEY (author_id) REFERENCES Authors(author_id)
FROM      
  INFORMATION_SCHEMA.book_id,"BOOK_ID","INT","PRIMARY KEY",AUTO_INCREAMENT
   INFORMATION_SCHEMA.title,"TITLE","VARCHAR","NOT NULL"
   INFORMATION_SCHEMA.author_id,"AUTHOR_ID","INT","NULLABLE"
   INFORMATION_SCHEMA.price,"PRICE","DOUBLE","NULLABLE"
   INFORMATION_SCHEMA.publication_date,"PUBLICATION_DATE","DATE","NULLABLE"
WHERE
   TABLE_SHEMA=ALX_BOOK_STORE() AND TABLE_NAME='Books';
